### ISSUE TITLE
#1 Plano de Iteração

### ISSUE THREAD

**Issue by uriell** [ditointernet/tradulab#10]
| Emoji               | Significado                                                                                             |
|:-------------------:|--------------------------------------------------------------------------------------------|
| :package:        | O item está em fase de QA (review)                |
| :muscle:           | O item é um objetivo bônus/extra da semana                                                           |
| :star2:              | Objetivo da semana (nós *realmente precisamos* entregar esse item) |

##### Cargos
- [x] Mapear quais permissões cada cargo deve conseguir gerenciar sobre os usuários de um projeto; :star2:
- [x] Restringir usuários de executar certas ações baseado nas permissões definidas anteriormente; :star2:

##### Arquivos
- [x] Estruturar o módulo de arquivos (constantes, resolvers, types, model); :star2:

##### Web
- [x] Instalar as primeiras dependências do projeto; :star2:
- [x] Testar a conexão com o back end subindo simultâneamente o Apollo Server e Apollo Client (no react); :star2:

**Comment by andyboli** [comment]
> Emoji	Significado
> 	O item está em fase de QA (review)
> 	O item é um objetivo bônus/extra da semana
> 	Objetivo da semana (nós _realmente precisamos_ entregar esse item)
> ### Categorias
> ##### Cargos
> * [ ]  Mapear quais permissões cada cargo deve conseguir gerenciar sobre os usuários de um projeto; star2
> * [ ]  Restringir usuários de executar certas ações baseado nas permissões definidas anteriormente; star2
> 
> ##### Arquivos
> * [ ]  Estruturar o módulo de arquivos (constantes, resolvers, types, model); star2
> 
> ##### Web
> * [ ]  Instalar as primeiras dependências do projeto; star2
> * [ ]  Testar a conexão com o back end subindo simultâneamente o Apollo Server e Apollo Client (no react); star2

**Comment by andyboli** [comment]
Translate - Traduzir uma frase;
Approve - revisar e aprovar uma tradução; 
Development - Tools de desenvolvimento (importar e exportar arquivos);
Management - Convidar colaboradores e alterar permissões;
{role: collaborator} -> Translate; 
{role: reviewer} -> Translate; Approve; 
{role: developer} -> Translate; Development; 
{role: manager} -> Translate; Approve; Development; Management (except owner); 
{role: owner} -> Translate; Approve; Development; Management; (just one exists)

**Comment by andyboli** [comment]
feature/feature-name
hotfix/fix-description

**Comment by andyboli** [comment]
Ativar o ambiente virtual e  subir o banco: docker-compose up -d mongo
Desativar o ambiente virtual: docker-compose down
Executar o Mongo Image: docker-compose exec mongo mongo

**Comment by andyboli** [comment]
mutation authOwner {
  createUser(user: {
    email: "uriell.viana@dito.com.br", 
    password: "123456",
    username: "uriell"
  }) {
    token
  }
}
​
mutation authContributor {
  createUser(user: {
    email: "uriell.viana+contributor@dito.com.br", 
    password: "123456",
    username: "uriell-contributor"
  }) {
    token
  }
}
​
# USER_ID - USERNAME             - JWT_TOKEN
# USER_ID - USERNAME_CONTRIBUTOR - JWT_TOKEN
​
mutation project {
  createProject(displayName: "Dito") {
  	id
    slug
    displayName
    owner {
      id
		}
    private
    createdAt
    updatedAt
  }
}
​
# PROJECT_SLUG - PROJECT_ID
​
mutation role {
	inviteUserToProject(
    projectId: "5fab0c65da43e54d35c78977",
    userId: "5fab08dcf8a6024912d59403",
    role: contributor
  ) {
    id
    role
    user {
      id
      displayName
    }
    project {
      id
      displayName
    }
    createdAt
    updatedAt
  }
}
​
query meOwner {
  me {
    id
  }
}
​
query meContributor {
  me {
    id
  }

**Comment by andyboli** [comment]
Material U
_https://material-ui.com/_

Google Fonts

_https://fonts.google.com/_
(Fina, Média, Grossa)

Roboto
Open Sans


**Theming - Meterial UI**

_https://material.io/inline-tools/color/_

cor que gera o primary: #59ab6c (400)

primary - blue
primary - green

secondary - green
secondary - red
secondary - orange/yellow

neutral - gray/black/white
