### ISSUE TITLE
#3 Plano de Iteração

### ISSUE THREAD

**Issue by andyboli** [ditointernet/tradulab#52]
Modules Backend
Phrases {
Processamento de um arquivo (json)
_id do arquivo
key
content
}
Suggestions {
_id phrase
language
user
text
score: [_id user]
}
Create Suggestion
Rate Suggestion
Delete Suggestions (Role ? )
Stats {
_id file
language
translation progress
approvel progress
}

**Comment by UriellViana** [comment]
Sugiro começarmos pela definição do module de suggestions: Acho que precisamos pensar em que tipo de interações os roles vão poder ter com uma suggestion né? O que um usuário vai poder fazer sobre um recurso que ele criou, e sobre recursos que outros criaram, e isso dependendo do cargo dele;

Acho que o de stats seria bem similar, porém só precisamos expor uma busca, já que a consolidação e quem vai salvar isso no banco provavelmente vai ser um microserviço (sim, um terceiro).

**Comment by Wxhbr** [comment]
> Sugiro começarmos pela definição do module de suggestions: Acho que precisamos pensar em que tipo de interações os roles vão poder ter com uma suggestion né? O que um usuário vai poder fazer sobre um recurso que ele criou, e sobre recursos que outros criaram, e isso dependendo do cargo dele;
> 
> Acho que o de stats seria bem similar, porém só precisamos expor uma busca, já que a consolidação e quem vai salvar isso no banco provavelmente vai ser um microserviço (sim, um terceiro).

O usuário vai entrar no tradulab pra fazer uma sugestão e vai encontrar 3 cenarios:

**Comment by UriellViana** [comment]
> Todas as roles, exceto collaborator, podem aprovar qualquer sugestão(Até sua propria??).
Colaborator e viewer, bom não esquecer q depois vamos ter um role abaixo do colaborator (pra não fazero codigo != colab e o viewer acabar com permissão de aprovar..).

**Comment by miguel-miguelito** [comment]
Acho que a própria pessoa (com exceção de colaborador pra baixo) pode sim aprovar sua própria sugestão.

E eu queria entender quais vão ser as principais diferenças entre um projeto público e privado (não só na parte de suggestions).

**Comment by andyboli** [comment]
Galera, pensei um pouco na modelagem das novas entidades do Tradulab e cheguei nesta conclusão.
Acho que **Rate** pode ser uma nova entidade, **Rate** esta para **User** e **Suggestions** assim como **Role** esta para **User** e **Project**.
Como um usuário pode ter uma role em um projeto, um usuário pode ter uma avaliação em uma sugestão.
Além do mais, tenho algunas motivos para acreditar que o approveProgress e o translateProgress devem serem calculados, em resolvers, a partir das entidades existes, ao invés de serem explicitamente expressos no banco de dados.
Os progressos são calculados(o que já indica que é uma operação, não uma propriedade) considerando o total de files que existe, quantas phrases foram aprovadas (approvelProgress), quantos phrases tem suggestions (translateProgress). Esses processos podem ser feitos já com a entidade que temos, podemos implementar um resolver que entregue o approveProgress e o translateProgress para ser usado (atualizado) no momento de renderização. Se implementarmos uma nova entidade no banco, vamos ter fazer muitas consultas neste para atualizar a informação, sendo que o que queremos de fato é um cálculo a partir de outras entidades. 
approvelProgress : Files -> Phrases by Language -> approvedSuggestions / totalPhrases
translateProgress: Files -> Phrases by Language -> suggestions / totalPhrases
![Screenshot from 2021-01-19 20-23-37](https://user-images.githubusercontent.com/55351352/105106925-a7656880-5a95-11eb-9602-b8a31b2f5677.png)

**Comment by Wxhbr** [comment]
Gostei desse seu esquema acho ficou muito bom!!! Agora em relação aos calculos, nesse jeito que vc ta falando pra fazer o calculo a gente precisaria fazer uma consulta no banco trazendo todas as frases e todas as sugestoes daquela frase para fazer o calculo neh e isso seria feito toda hora que a pessoa entrasse na aba de files acredito eu. Minha duvida é que as vezes a gente fazendo isso no banco de dados seja mais rapido, por ex fazendo uma funçao do proprio banco na hora que salvar uma sugestão, nesse caso, sempre q salvasse a sugestão ele faria essa conta e atualizaria os valores no banco. Qual seria a melhor abordagem eu não sei, teria que calcular qto tempo que demoraria pra isso.

**Comment by andyboli** [comment]
@Wxhbr , então, ao meu ver, tem que ver a opinião do Uriell ou Rogério, calcular esses valores no momento em que eles forem solicitados me parece a maneira mais correta.

**Comment by Wxhbr** [comment]
Eu acho que faz sentido o que vc falou sim, eu só não tenho muito conhecimento de banco de dados pra afirmar que seria melhor fazer do seu jeito. Na minha mente parece que ficaria mais otimizado dessa forma que vc falou de calcular somente qndo precisasse. Eu vou pesquisar um pouco sobre operacoes no banco de dados pra ver sobre isso aqui.

**Comment by Wxhbr** [comment]
Eu dei uma pesquisada rapida aqui e acho melhor fazer sim da forma como vc propos, principalmente, pq a gente ta usando Mongo e não SQL como tava na minha mente kkkkkk. Pelo que eu li não é interessante fazer operações javascript dentro do MongoDB e ele não possui aqueles triggers/viwers e talz do SQL, então, realmente não teria sentido isso ser calculado dentro do banco de dados. Agora a questão é será realmente desnecessário ter esses campos dentro do banco de dados de approval progress e translate progress, nunca vai ser necessário que eles estejam no banco será?

**Comment by UriellViana** [comment]
Minha sugestão de salvar isso é por receio de uma operação cara como uma agregação ser repetida livremente toda vez que alguém acessa. Num projeto muito grande essa agregação pode ficar lenta, e ser realizada desnecessariamente quando o resultado final não mudou. **Lembrem que a gente quer entregar um % de tradução e aprovação pra cada idioma distinto, somado a partir das N files disponiveis.**

Pra exemplo, hoje o dashboard tem ~2000 phrases, e a gente nem migrou 20% do que o CRM tem pra lá.. Pensem que suggestions vão ter muito mais documentos do que phrases.

Depois que definirmos o modelo de suggestion e phrases, sugiro fazer um script que vai popular 10k de registros de frases e 7.5k de registros de suggestions (75% das phrases teriam tradução, as 2.5k restantes seriam incrementadas como sugestões "extra" de alguma frase já traduzida). Isso seria pra um idioma, e a partir daí a gente repete isso pra ~100 idiomas, totalizando 1M de documentos no banco que teriam que ser percorridos e agregados pra cada visita na tela.

E rodar algumas queries de agregação pra ver a performance. Se não me engano, seriam três counts no banco:
1. `SELECT COUNT(DISTINCT id) total_phrases FROM phrases WHERE project_id = "____"`;
2. `SELECT language, COUNT(DISTINCT phrase_id) FROM suggestions WHERE project_id = "____"  AND approved = TRUE GROUP BY language`;
3. `SELECT language, COUNT(DISTINCT phrase_id) FROM suggestions WHERE project_id = "____" GROUP BY language`

Essas seriam as agregações que precisariamos fazer (eu escrevi SQL mas pq não sei de cabeça como fazer no MongoDB). Se quiserem eu posso fazer esse teste com vocês mas acho que não vale o esforço pra já se precaver dessa preocupação.

**Comment by miguel-miguelito** [comment]
Eu gostei da sugestão de fazer o Rating como entidade separada. O que você acha disso, @UriellViana ? Considerando inclusive essas questões de consultas ao banco de dados, teria alguma diferença?

**Comment by UriellViana** [comment]
Sobre o Rating, eu acho que poderia ser feito isso mais tarde, a solução de array de ids como só "+1" é a mais rápida de fazer, consideramos que queremos uma primera versão logo.

**Comment by miguel-miguelito** [comment]
O Model de Suggestion está pronto para o review. Pensei em continuar esse módulo, fazendo os resolvers, porém acho que não vai dar muito certo sem ter feito a parte de Phrase antes, porque toda suggestion referencia uma phrase. O que vocês acham?

**Comment by andyboli** [comment]
@UriellViana então, você sugere que **approveProgess** e **TranslateProgess** sejam _propriedades_ da entidade File, certo? Você pode descrever pra mim **quais seriam os processos que atualizariam estas informaçẽos em Files e qual seria a complexidade destas operações?**. Como um exemplo vamos considerar o caso de uso de **atualizar um File**, neste modelo de dados, nesta operação seria necessário atualizar o valor de **approvelProgress** e **translateProgress**, as operações necessária para realizar esta atualização não exigiriam uma iteração para se achar o _total de Files_, o _total de Pharses_ (lembrando que pharses podem ser deletadas), o _total de Suggestions_, da mesma forma? E em outros casos, como **dar uma suggestion**, não exigiria também um recálculo de translateProgress, ou seja, mais iteração, mais consulta. Fora que ambos os casos fica completamente _implicito_ a **atualização do translateProgress**. Eu achei sua resposta foda, entendi super a complexidade da consulta, eu só ainda preciso de um **esclarecimento maior, em nível de código, do outro lado da moeda**. Talvez em meio este tanto de requisição tem como fazer o usuário enviar mais informação, logo exigiria menos consultas, mas ainda não consigo ver isso claramente.

**Comment by andyboli** [comment]
@UriellViana mas o que achou da ideia do Rating, esta correta? Eu entendo que talvez levaria mais tempo, talvez para definir os resolvers, mas eu acho que compensa mais modelar esta entidade de uma vez, mas isso se a ideia tiver coesa. **Rate esta para User e Suggestions assim como Role esta para User e Project**, isso é verdade?

**Comment by UriellViana** [comment]
>você sugere que approvelProgess e TranslateProgess sejam propriedades da entidade File, certo?

não, já invalidamos essa idéia porque queremos ter os progressos por idioma, e só existe um file.. é a entidade stats que eu mencionei anteriormente.

>como dar uma suggestion, não exigiria também um recálculo de translateProgress, ou seja, mais iteração, mais consulta

sim e não, não temos necessidade de atualizar "real time" os progressos de tradução e aprovação.. não dá pra fazer muito trabalho em curto espaço de tempo, então algo como uma atualização a cada hora já serviria..

>quais seriam os processos que atualizariam estas informaçẽos

eu imagino que um microserviço seria mais adequado pra esse tipo de consolidação

**Comment by UriellViana** [comment]
Eu gostei da sugestão de entidade Rating, mas ainda acho que não é necessário no momento

>compensa mais modelar esta entidade de uma vez, para uma primeira versão ter um banco de dados bem definido pode ser valioso para o futuro, não?

não acho que tem necessidade de ser modelado no banco nesse momento, o esforço é baixo pra introduzir isso mais tarde
